DymmyNet/DymmyNet.Web/Controllers/FriendsController.cs
namespace DymmyNet.Web.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using DummyNet.Common;
    using ViewModels;

    /// <summary>
    /// Контроллер страницы друзей
    /// </summary>
    [System.Web.Mvc.Authorize]
    public class FriendsController : Controller
    {
        /// <summary>
        /// Менеджер отношений между пользователями
        /// </summary>
        private readonly IRelationshipsManager relationshipsManager;

        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="FriendsController"/>.
        /// </summary>
        /// <param name="relationshipsManager">
        /// The relationships manager.
        /// </param>
        public FriendsController(IRelationshipsManager relationshipsManager)
        {
            this.relationshipsManager = relationshipsManager;
        }

        /// <summary>
        /// Отображенние всех друзей
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Index()
        {
            ViewBag.MyNick = User.Identity.Name;
            var vm = new UsersListViewModel(relationshipsManager.FindSubscriptions(User.Identity.Name));
            ReplaceAvatarUrl(vm.Users);
            return View(vm);
        }

        /// <summary>
        /// Изменение Url аватара на полный адрес
        /// </summary>
        /// <param name="collection">
        /// The collection.
        /// </param>
        private void ReplaceAvatarUrl(IEnumerable<UserViewModel> collection)
        {
            foreach (var vm in collection)
            {
                vm.Avatar = string.Format(
                    "{0}://{1}/UsersContent/{2}",
                    Request.Url.Scheme,
                    Request.Url.Authority,
                    vm.Avatar);
            }
        }
    }
}

DymmyNet/DymmyNet.Web/Controllers/IMController.cs
namespace DymmyNet.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    using DummyNet.Common;

    using DymmyNet.Web.ViewModels;

    /// <summary>
    /// Контроллер сообщений
    /// </summary>
    [System.Web.Mvc.Authorize]
    public class IMController : Controller
    {
        /// <summary>
        /// Менеджер разговоров
        /// </summary>
        private readonly IConversationManager conversationManager;

        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="IMController"/>.
        /// </summary>
        /// <param name="conversationManager">
        /// The conversation manager.
        /// </param>
        public IMController(IConversationManager conversationManager)
        {
            this.conversationManager = conversationManager;
        }

        /// <summary>
        /// Просто отдадим список разговоров
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Index()
        {
            var viewModels = new List<ConversationViewModel>();
            return View(viewModels);
        }
    }
}

DymmyNet/DymmyNet.Web/Controllers/SearchController.cs
namespace DymmyNet.Web.Controllers
{
    using System.Collections.Generic;
    using System.Web.Http;
    using System.Web.Mvc;

    using DummyNet.Common;

    using DymmyNet.Web.ViewModels;

    /// <summary>
    /// Контроллер поиска
    /// </summary>
    [System.Web.Mvc.Authorize]
    public class SearchController : Controller
    {
        /// <summary>
        /// Менеджер пользователей
        /// </summary>
        private readonly IUsersManager usersManager;

        /// <summary>
        /// Инициализирует новый экземпляр класса <see cref="SearchController"/>.
        /// </summary>
        /// <param name="usersManager">
        /// The users manager.
        /// </param>
        public SearchController(IUsersManager usersManager)
        {
            this.usersManager = usersManager;
        }

        /// <summary>
        /// Поиск пользователя
        /// </summary>
        /// <param name="searchstring">
        /// The searchstring.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Index([FromUri]string searchstring)
        {
            if (searchstring != null)
            {
                var users = new UsersListViewModel(usersManager.FindUsers(searchstring.Split(' ')));
                ReplaceAvatarUrl(users.Users);
                return View(users);
            }
            else
            {
                return View(new UsersListViewModel());
            }
        }

        /// <summary>
        /// Замена url аватара на полный
        /// </summary>
        /// <param name="collection">Коллекция пользователей</param>
        private void ReplaceAvatarUrl(IEnumerable<UserViewModel> collection)
        {
            foreach (var vm in collection)
            {
                vm.Avatar = string.Format(
                    "{0}://{1}/UsersContent/{2}",
                    Request.Url.Scheme,
                    Request.Url.Authority,
                    vm.Avatar);
            }
        }
    }
}

DymmyNet/DymmyNet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title – приложение ASP.NET MVC</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    
    @Styles.Render("~/Content/css")
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    

<div id="mainMenu">
    @Html.Partial("_MainMenu")
</div>

<div id="body">
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/ajaxlogin")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

DymmyNet/DymmyNet.Web/Views/Shared/_MainMenu.cshtml
@if (Request.IsAuthenticated) {
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DummyNet", "Index" , "Home", new {id = ViewBag.MyNick }, new {@class="navbar-brand"})
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Моя страница", "Index", "Home", new { id = ViewBag.MyNick }, null)</li>
                    <li>@Html.ActionLink("Друзья", "Index", "Friends")</li>
                    <li>@Html.ActionLink("Сообщения", "Index", "IM")</li>
                    <li><a href="#"></a></li>
                </ul>
                <form class="navbar-form navbar-left" role="search" action="@Url.Action("Index", "Search")" method="GET">
                    <div class="form-group">
                        <input type="text" class="form-control" name="searchstring" placeholder="Поиск">
                    </div>
                    <button type="submit" class="btn btn-default">Поиск</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Профиль<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: new { area = "" }, htmlAttributes: new { @class = "username", title = "Manage" })</li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
        @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" }))
        {
            @Html.AntiForgeryToken()
        }
    </nav>
}